// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzBN9a1R1-_W-mfzpT4BG3AM0SJI979c',
    appId: '1:115776664280:web:dbbc9e753b5e1866c21dad',
    messagingSenderId: '115776664280',
    projectId: 'biodigester-cd495',
    authDomain: 'biodigester-cd495.firebaseapp.com',
    storageBucket: 'biodigester-cd495.firebasestorage.app',
    measurementId: 'G-WKYDJGDPGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbrRFf-lJTsolJv88WlG0Kna_0PvE9Mw',
    appId: '1:115776664280:android:124aec9fc5c93cdbc21dad',
    messagingSenderId: '115776664280',
    projectId: 'biodigester-cd495',
    storageBucket: 'biodigester-cd495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fl59b2ieP7KgHHbERzDHWoU1B2hm2OE',
    appId: '1:115776664280:ios:55bddca5ee35b756c21dad',
    messagingSenderId: '115776664280',
    projectId: 'biodigester-cd495',
    storageBucket: 'biodigester-cd495.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fl59b2ieP7KgHHbERzDHWoU1B2hm2OE',
    appId: '1:115776664280:ios:55bddca5ee35b756c21dad',
    messagingSenderId: '115776664280',
    projectId: 'biodigester-cd495',
    storageBucket: 'biodigester-cd495.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
